name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: release-drafter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@693d20e7c1ce1a81d3a41962f85914253b518449
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
